import { db, servicesTable, providersTable, notificationsTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { logger } from "./logger";
import { USER_ID } from "./constants";

const SERVICES = [
  {
    slug: "home-deep-cleaning",
    name: "Home Deep Cleaning",
    category: "cleaning",
    description: "Complete deep cleaning of your home including kitchen, bathrooms, bedrooms and living areas. Our trained professionals use eco-friendly products.",
    startingPrice: 999,
    rating: 4.8,
    reviewCount: 2847,
    duration: "3-4 hours",
    imageKey: "cleaning",
    popular: true,
  },
  {
    slug: "bathroom-cleaning",
    name: "Bathroom Cleaning",
    category: "cleaning",
    description: "Deep cleaning and sanitization of bathrooms. Includes scrubbing tiles, cleaning fixtures and sanitizing all surfaces.",
    startingPrice: 299,
    rating: 4.7,
    reviewCount: 1923,
    duration: "1-2 hours",
    imageKey: "cleaning",
    popular: false,
  },
  {
    slug: "sofa-cleaning",
    name: "Sofa & Upholstery Cleaning",
    category: "cleaning",
    description: "Professional cleaning of sofas, couches and fabric furniture using steam cleaning and stain removal.",
    startingPrice: 799,
    rating: 4.7,
    reviewCount: 1102,
    duration: "2-3 hours",
    imageKey: "cleaning",
    popular: false,
  },
  {
    slug: "pipe-leak-repair",
    name: "Pipe Leak Repair",
    category: "plumbing",
    description: "Expert diagnosis and repair of pipe leaks. We fix dripping taps, leaking pipes and damaged fittings.",
    startingPrice: 399,
    rating: 4.9,
    reviewCount: 1245,
    duration: "1-2 hours",
    imageKey: "plumbing",
    popular: true,
  },
  {
    slug: "blocked-drain-cleaning",
    name: "Blocked Drain Cleaning",
    category: "plumbing",
    description: "Professional unblocking of kitchen, bathroom or outdoor drains using advanced equipment.",
    startingPrice: 499,
    rating: 4.6,
    reviewCount: 876,
    duration: "1-3 hours",
    imageKey: "plumbing",
    popular: false,
  },
  {
    slug: "water-heater-repair",
    name: "Water Heater Repair",
    category: "plumbing",
    description: "Diagnosis and repair of geyser and water heater issues. Includes element replacement, thermostat fixes.",
    startingPrice: 599,
    rating: 4.8,
    reviewCount: 731,
    duration: "1-2 hours",
    imageKey: "plumbing",
    popular: true,
  },
  {
    slug: "electrical-wiring",
    name: "Electrical Wiring",
    category: "electrical",
    description: "Safe and certified electrical wiring for new rooms, renovations or replacement of faulty wiring.",
    startingPrice: 799,
    rating: 4.8,
    reviewCount: 543,
    duration: "2-4 hours",
    imageKey: "electrical",
    popular: false,
  },
  {
    slug: "fan-installation",
    name: "Fan Installation",
    category: "electrical",
    description: "Professional installation of ceiling fans, wall fans and exhaust fans with proper wiring.",
    startingPrice: 299,
    rating: 4.9,
    reviewCount: 3201,
    duration: "30-60 min",
    imageKey: "electrical",
    popular: true,
  },
  {
    slug: "switch-socket-repair",
    name: "Switch & Socket Repair",
    category: "electrical",
    description: "Safe replacement and repair of switches, sockets and electrical boards. ISI certified components used.",
    startingPrice: 199,
    rating: 4.8,
    reviewCount: 2145,
    duration: "30-60 min",
    imageKey: "electrical",
    popular: true,
  },
  {
    slug: "womens-haircut",
    name: "Women's Haircut",
    category: "salon",
    description: "Professional haircut and styling by certified beauticians at your home. Includes wash and blow dry.",
    startingPrice: 449,
    rating: 4.8,
    reviewCount: 4532,
    duration: "1-2 hours",
    imageKey: "salon",
    popular: true,
  },
  {
    slug: "manicure-pedicure",
    name: "Manicure & Pedicure",
    category: "salon",
    description: "Complete nail care service including filing, cuticle care, buffing and nail polish application.",
    startingPrice: 599,
    rating: 4.7,
    reviewCount: 2198,
    duration: "1.5 hours",
    imageKey: "salon",
    popular: false,
  },
  {
    slug: "facial-and-cleanup",
    name: "Facial & Cleanup",
    category: "salon",
    description: "Deep cleansing facial treatment with premium products. Removes dead skin, unclogs pores and brightens skin.",
    startingPrice: 799,
    rating: 4.9,
    reviewCount: 1876,
    duration: "1 hour",
    imageKey: "salon",
    popular: true,
  },
  {
    slug: "wall-painting",
    name: "Wall Painting",
    category: "painting",
    description: "Professional interior wall painting with quality paints. Includes surface preparation and two coats.",
    startingPrice: 1499,
    rating: 4.6,
    reviewCount: 891,
    duration: "1-2 days",
    imageKey: "painting",
    popular: false,
  },
  {
    slug: "waterproofing",
    name: "Waterproofing",
    category: "painting",
    description: "Expert waterproofing of terrace, bathroom and external walls to prevent seepage and leakage.",
    startingPrice: 2999,
    rating: 4.7,
    reviewCount: 456,
    duration: "1-2 days",
    imageKey: "painting",
    popular: false,
  },
  {
    slug: "cockroach-control",
    name: "Cockroach Control",
    category: "pest",
    description: "Safe and effective cockroach extermination treatment. Child and pet safe gel-based treatment.",
    startingPrice: 699,
    rating: 4.7,
    reviewCount: 1567,
    duration: "1-2 hours",
    imageKey: "pest",
    popular: true,
  },
  {
    slug: "termite-control",
    name: "Termite Control",
    category: "pest",
    description: "Comprehensive termite inspection and treatment. Protect your furniture and wooden structures.",
    startingPrice: 1999,
    rating: 4.8,
    reviewCount: 823,
    duration: "2-4 hours",
    imageKey: "pest",
    popular: false,
  },
  {
    slug: "carpentry-repair",
    name: "Carpentry Repair",
    category: "carpentry",
    description: "Expert repair of wooden furniture, cabinets, doors and windows. Includes joints, hinges and polish.",
    startingPrice: 599,
    rating: 4.7,
    reviewCount: 643,
    duration: "1-3 hours",
    imageKey: "carpentry",
    popular: false,
  },
  {
    slug: "ac-service",
    name: "AC Service & Repair",
    category: "appliances",
    description: "Complete air conditioner servicing including cleaning, gas check and performance optimization.",
    startingPrice: 799,
    rating: 4.8,
    reviewCount: 2341,
    duration: "1-2 hours",
    imageKey: "appliances",
    popular: true,
  },
  {
    slug: "washing-machine-repair",
    name: "Washing Machine Repair",
    category: "appliances",
    description: "Expert repair of all brands of washing machines. Covers motor, drum, board and valve issues.",
    startingPrice: 499,
    rating: 4.7,
    reviewCount: 1234,
    duration: "1-2 hours",
    imageKey: "appliances",
    popular: true,
  },
];

const PROVIDERS = [
  {
    slug: "rahul-sharma",
    name: "Rahul Sharma",
    initials: "RS",
    rating: 4.9,
    reviewCount: 342,
    jobsCompleted: 1256,
    specializations: ["Deep Cleaning", "Office Cleaning", "Move-in Cleaning"],
    experience: "5 years",
    verified: true,
    category: "cleaning",
  },
  {
    slug: "priya-patel",
    name: "Priya Patel",
    initials: "PP",
    rating: 4.8,
    reviewCount: 289,
    jobsCompleted: 987,
    specializations: ["Haircut", "Facial", "Manicure"],
    experience: "4 years",
    verified: true,
    category: "salon",
  },
  {
    slug: "amit-kumar",
    name: "Amit Kumar",
    initials: "AK",
    rating: 4.9,
    reviewCount: 412,
    jobsCompleted: 1589,
    specializations: ["Pipe Repair", "Drain Cleaning", "Bathroom Fitting"],
    experience: "7 years",
    verified: true,
    category: "plumbing",
  },
  {
    slug: "sunita-devi",
    name: "Sunita Devi",
    initials: "SD",
    rating: 4.7,
    reviewCount: 178,
    jobsCompleted: 634,
    specializations: ["Home Cleaning", "Kitchen Deep Clean"],
    experience: "3 years",
    verified: true,
    category: "cleaning",
  },
  {
    slug: "vikram-singh",
    name: "Vikram Singh",
    initials: "VS",
    rating: 4.8,
    reviewCount: 267,
    jobsCompleted: 892,
    specializations: ["Wiring", "Fan Installation", "Switch Repair"],
    experience: "6 years",
    verified: true,
    category: "electrical",
  },
  {
    slug: "meena-joshi",
    name: "Meena Joshi",
    initials: "MJ",
    rating: 4.9,
    reviewCount: 198,
    jobsCompleted: 723,
    specializations: ["Facial", "Hair Color", "Waxing"],
    experience: "5 years",
    verified: true,
    category: "salon",
  },
  {
    slug: "raju-electrician",
    name: "Raju Verma",
    initials: "RV",
    rating: 4.8,
    reviewCount: 321,
    jobsCompleted: 1102,
    specializations: ["AC Repair", "Wiring", "MCB Fitting"],
    experience: "8 years",
    verified: true,
    category: "electrical",
  },
  {
    slug: "deepak-plumber",
    name: "Deepak Nair",
    initials: "DN",
    rating: 4.7,
    reviewCount: 234,
    jobsCompleted: 867,
    specializations: ["Water Heater", "Tap Repair", "Drain Cleaning"],
    experience: "4 years",
    verified: true,
    category: "plumbing",
  },
];

export async function seedDatabase() {
  try {
    const existingServices = await db.select().from(servicesTable).limit(1);
    if (existingServices.length === 0) {
      logger.info("Seeding database...");
      await db.insert(servicesTable).values(SERVICES);
      await db.insert(providersTable).values(PROVIDERS);
      logger.info("Services and providers seeded");
    } else {
      logger.info("Services already seeded, skipping");
    }

    const existingNotifs = await db
      .select()
      .from(notificationsTable)
      .where(eq(notificationsTable.userId, USER_ID))
      .limit(1);

    if (existingNotifs.length === 0) {
      await db.insert(notificationsTable).values([
        {
          userId: USER_ID,
          type: "welcome",
          icon: "gift",
          iconColor: "#f97316",
          title: "Welcome to Urban!",
          body: "Book your first service and get 20% off. Use code: FIRST20",
          read: false,
        },
        {
          userId: USER_ID,
          type: "offer",
          icon: "tag",
          iconColor: "#8b5cf6",
          title: "Special Weekend Offer",
          body: "Get 30% off on all cleaning services this weekend. Limited time only!",
          read: false,
        },
      ]);
      logger.info("Default notifications seeded");
    }
  } catch (err) {
    logger.error({ err }, "Failed to seed database");
  }
}
